Project Overview

IT Helpdesk Tickets

IT Helpdesk Performance Analysis is a Python and Pandas project that analyzes IT support tickets to identify trends in ticket volume, resolution time, SLA breaches, team performance, and customer satisfaction. The project uses data analysis and visualization to generate insights and improve helpdesk efficiency.

Import Required Libraries

Importing Required Libraries The following Python libraries will be used throughout the project. Pandas and NumPy will support data manipulation and numerical analysis, while Matplotlib, Seaborn, and Plotly will be used to create visualizations.

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [31]:
df = pd.read_csv(r"C:\Users\NAMITHA\Downloads\it_helpdesk_tickets.csv")
df.head()

,ticket_id,created_date,resolved_date,category,priority,sla_target_hours,first_response_hours,resolution_time_hours,sla_breached,status,assigned_team,agent_name,location,channel,customer_satisfaction
0,INC100208,2025-01-01 12:06:25,2025-01-01 19:34:37,Access Management,Low,48,7.47,7.47,False,Closed,Security Team,L. Fernandes,Branch - New York,Email,5.0
1,INC100123,2025-01-01 13:36:24,2025-01-02 09:32:12,Printer,High,8,2.31,19.93,True,Resolved,Security Team,H. Osei,HQ - Dubai,Walk-in,4.0
2,INC100671,2025-01-01 13:38:35,2025-01-02 00:06:11,Software,High,8,3.20,10.46,True,Closed,Service Desk L1,E. Zhou,Branch - London,Self-Service Portal,1.0
3,INC100254,2025-01-01 16:58:07,2025-01-01 17:34:07,Email,High,8,0.60,0.60,False,Reopened,Network Ops,G. Petrov,HQ - Dubai,Self-Service Portal,NaN
4,INC101299,2025-01-01 17:52:03,2025-01-02 11:20:15,Printer,High,8,1.75,17.47,True,Resolved,App Support,H. Osei,HQ - Dubai,Self-Service Portal,4.0

In [32]:
df.tail()

,ticket_id,created_date,resolved_date,category,priority,sla_target_hours,first_response_hours,resolution_time_hours,sla_breached,status,assigned_team,agent_name,location,channel,customer_satisfaction
2995,INC102114,2025-12-31 14:15:22,2026-01-02 05:39:22,Software,Low,48,21.05,39.40,False,Resolved,Desktop Support,E. Zhou,HQ - Dubai,Self-Service Portal,4.0
2996,INC100442,2025-12-31 14:49:54,2025-12-31 21:54:06,Application Support,High,8,3.49,7.07,False,Reopened,Systems Admin,E. Zhou,Remote,Self-Service Portal,NaN
2997,INC102401,2025-12-31 16:21:15,2026-01-02 09:31:27,Application Support,Low,48,1.66,41.17,False,Closed,App Support,A. Khan,Remote,Self-Service Portal,5.0
2998,INC102493,2025-12-31 22:19:55,2026-01-01 14:45:43,Email,Medium,24,1.78,16.43,False,Closed,Network Ops,F. Torres,Remote,Email,4.0
2999,INC100570,2025-12-31 22:33:23,2026-01-01 07:42:59,Printer,Medium,24,0.75,9.16,False,Resolved,Systems Admin,A. Khan,Branch - Singapore,Self-Service Portal,3.0

Initial Dataset Overview

Before performing any cleaning or analysis, the dataset will be examined to understand its size, structure, variable types, and initial characteristics. This step helps identify potential data quality issues that need to be addressed during preprocessing.

In [33]:
print("Number of rows:",df.shape[0])
print("Number of Columns:", df.shape[1])

Number of rows: 3000
Number of Columns: 15

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              3000 non-null   str
 1   created_date           3000 non-null   str
 2   resolved_date          2862 non-null   str
 3   category               3000 non-null   str
 4   priority               3000 non-null   str
 5   sla_target_hours       3000 non-null   int64
 6   first_response_hours   3000 non-null   float64
 7   resolution_time_hours  3000 non-null   float64
 8   sla_breached           3000 non-null   bool
 9   status                 3000 non-null   str
 10  assigned_team          3000 non-null   str
 11  agent_name             3000 non-null   str
 12  location               3000 non-null   str
 13  channel                3000 non-null   str
 14  customer_satisfaction  2523 non-null   float64
dtypes: bool(1), float64(3), int64(1), str(10)
memory usage: 331.2 KB

In [35]:
df.dtypes

ticket_id                    str
created_date                 str
resolved_date                str
category                     str
priority                     str
sla_target_hours           int64
first_response_hours     float64
resolution_time_hours    float64
sla_breached                bool
status                       str
assigned_team                str
agent_name                   str
location                     str
channel                      str
customer_satisfaction    float64
dtype: object

In [36]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ticket_id,3000,3000,INC100208,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_date,3000,3000,2025-01-01 12:06:25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved_date,2862,2862,2025-01-01 19:34:37,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,3000,8,Software,583,NaN,NaN,NaN,NaN,NaN,NaN,NaN
priority,3000,4,Low,1068,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sla_target_hours,3000.0,NaN,NaN,NaN,27.408,16.780288,4.0,8.0,24.0,48.0,48.0
first_response_hours,3000.0,NaN,NaN,NaN,6.33766,5.852206,0.05,1.69,4.15,9.4,23.93
resolution_time_hours,3000.0,NaN,NaN,NaN,21.773883,25.648795,0.29,5.91,13.575,27.6075,288.0
sla_breached,3000,2,False,2258,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,3000,3,Resolved,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN
assigned_team,3000,6,Security Team,553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agent_name,3000,12,D. Ahmed,273,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,3000,5,HQ - Dubai,1038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
channel,3000,5,Email,896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_satisfaction,2523.0,NaN,NaN,NaN,3.98692,0.916967,1.0,3.0,4.0,5.0,5.0

In [37]:
df.describe()

,sla_target_hours,first_response_hours,resolution_time_hours,customer_satisfaction
count,3000.000000,3000.000000,3000.000000,2523.000000
mean,27.408000,6.337660,21.773883,3.986920
std,16.780288,5.852206,25.648795,0.916967
min,4.000000,0.050000,0.290000,1.000000
25%,8.000000,1.690000,5.910000,3.000000
50%,24.000000,4.150000,13.575000,4.000000
75%,48.000000,9.400000,27.607500,5.000000
max,48.000000,23.930000,288.000000,5.000000

In [38]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns.tolist()

['ticket_id',
 'created_date',
 'resolved_date',
 'category',
 'priority',
 'sla_target_hours',
 'first_response_hours',
 'resolution_time_hours',
 'sla_breached',
 'status',
 'assigned_team',
 'agent_name',
 'location',
 'channel',
 'customer_satisfaction']

Missing Value Assessment
The dataset will be examined for missing values to determine whether any variables contain incomplete observations. The number and percentage of missing values will be calculated to support decisions regarding appropriate treatment.

In [39]:
# Calculate the number of missing values
missing_count=df.isnull().sum()

# Calculate the percentage of missing value
missing_percentage= df.isnull().sum()/len(df)*100

# Create a summary table
missing_summary=pd.DataFrame({'Missing Values':missing_count,
                              'Missing Percentage':missing_percentage})
missing_summary.sort_values(
    by='Missing Values',
    ascending=False
)
# Display the summary
missing_summary

                       Missing Values  Missing Percentage
ticket_id                           0                 0.0
created_date                        0                 0.0
resolved_date                     138                 4.6
category                            0                 0.0
priority                            0                 0.0
sla_target_hours                    0                 0.0
first_response_hours                0                 0.0
resolution_time_hours               0                 0.0
sla_breached                        0                 0.0
status                              0                 0.0
assigned_team                       0                 0.0
agent_name                          0                 0.0
location                            0                 0.0
channel                             0                 0.0
customer_satisfaction             477                15.9

In [40]:
df["category"].unique()

<StringArray>
[  'Access Management',             'Printer',            'Software',
               'Email', 'Application Support',            'Hardware',
             'Network',   'Security Incident']
Length: 8, dtype: str

In [41]:
df["priority"].unique()

<StringArray>
['Low', 'High', 'Medium', 'Critical']
Length: 4, dtype: str

In [42]:
df["sla_target_hours"].unique()

array([48,  8, 24,  4])

In [43]:
df["status"].unique()

<StringArray>
['Closed', 'Resolved', 'Reopened']
Length: 3, dtype: str

In [44]:
df["assigned_team"].unique()

<StringArray>
[  'Security Team', 'Service Desk L1',     'Network Ops',     'App Support',
   'Systems Admin', 'Desktop Support']
Length: 6, dtype: str

In [45]:
df["agent_name"].unique()

<StringArray>
['L. Fernandes',      'H. Osei',      'E. Zhou',    'G. Petrov',
    'F. Torres',     'K. Meyer',      'A. Khan',     'C. Novak',
     'I. Rossi',     'D. Ahmed',       'J. Kim',     'B. Silva']
Length: 12, dtype: str

In [46]:
df["location"].unique()

<StringArray>
[ 'Branch - New York',         'HQ - Dubai',    'Branch - London',
             'Remote', 'Branch - Singapore']
Length: 5, dtype: str

In [47]:
df["channel"].unique()

<StringArray>
['Email', 'Walk-in', 'Self-Service Portal', 'Chat', 'Phone']
Length: 5, dtype: str

In [48]:
df["customer_satisfaction"].unique()

array([ 5.,  4.,  1., nan,  3.,  2.])

In [49]:
# Convert datatypes

df["created_date"] = pd.to_datetime(df["created_date"])
df["resolved_date"] = pd.to_datetime(df["resolved_date"])

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              3000 non-null   str
 1   created_date           3000 non-null   datetime64[us]
 2   resolved_date          2862 non-null   datetime64[us]
 3   category               3000 non-null   str
 4   priority               3000 non-null   str
 5   sla_target_hours       3000 non-null   int64
 6   first_response_hours   3000 non-null   float64
 7   resolution_time_hours  3000 non-null   float64
 8   sla_breached           3000 non-null   bool
 9   status                 3000 non-null   str
 10  assigned_team          3000 non-null   str
 11  agent_name             3000 non-null   str
 12  location               3000 non-null   str
 13  channel                3000 non-null   str
 14  customer_satisfaction  2523 non-null   float64
dtypes: bool(1), datetime64[us](2), float64(3), int64(1), str(8)
memory usage: 331.2 KB

In [51]:
df = df.drop_duplicates()

In [52]:
df.isnull().sum()

ticket_id                  0
created_date               0
resolved_date            138
category                   0
priority                   0
sla_target_hours           0
first_response_hours       0
resolution_time_hours      0
sla_breached               0
status                     0
assigned_team              0
agent_name                 0
location                   0
channel                    0
customer_satisfaction    477
dtype: int64

In [53]:
df.columns = df.columns.str.strip()

In [54]:
# Remove spaces from text columns
text_cols = df.select_dtypes(include="str").columns
df[text_cols] = df[text_cols].apply(lambda x: x.str.strip())

In [55]:
df.isnull().sum()

ticket_id                  0
created_date               0
resolved_date            138
category                   0
priority                   0
sla_target_hours           0
first_response_hours       0
resolution_time_hours      0
sla_breached               0
status                     0
assigned_team              0
agent_name                 0
location                   0
channel                    0
customer_satisfaction    477
dtype: int64

status = Reopened
resolved_date is present
customer_satisfaction = NaN

So the missing customer_satisfaction is likely because the customer didn't provide a survey response, rather than because the row is invalid.

In [56]:
df

,ticket_id,created_date,resolved_date,category,priority,sla_target_hours,first_response_hours,resolution_time_hours,sla_breached,status,assigned_team,agent_name,location,channel,customer_satisfaction
0,INC100208,2025-01-01 12:06:25,2025-01-01 19:34:37,Access Management,Low,48,7.47,7.47,False,Closed,Security Team,L. Fernandes,Branch - New York,Email,5.0
1,INC100123,2025-01-01 13:36:24,2025-01-02 09:32:12,Printer,High,8,2.31,19.93,True,Resolved,Security Team,H. Osei,HQ - Dubai,Walk-in,4.0
2,INC100671,2025-01-01 13:38:35,2025-01-02 00:06:11,Software,High,8,3.20,10.46,True,Closed,Service Desk L1,E. Zhou,Branch - London,Self-Service Portal,1.0
3,INC100254,2025-01-01 16:58:07,2025-01-01 17:34:07,Email,High,8,0.60,0.60,False,Reopened,Network Ops,G. Petrov,HQ - Dubai,Self-Service Portal,NaN
4,INC101299,2025-01-01 17:52:03,2025-01-02 11:20:15,Printer,High,8,1.75,17.47,True,Resolved,App Support,H. Osei,HQ - Dubai,Self-Service Portal,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,INC102114,2025-12-31 14:15:22,2026-01-02 05:39:22,Software,Low,48,21.05,39.40,False,Resolved,Desktop Support,E. Zhou,HQ - Dubai,Self-Service Portal,4.0
2996,INC100442,2025-12-31 14:49:54,2025-12-31 21:54:06,Application Support,High,8,3.49,7.07,False,Reopened,Systems Admin,E. Zhou,Remote,Self-Service Portal,NaN
2997,INC102401,2025-12-31 16:21:15,2026-01-02 09:31:27,Application Support,Low,48,1.66,41.17,False,Closed,App Support,A. Khan,Remote,Self-Service Portal,5.0
2998,INC102493,2025-12-31 22:19:55,2026-01-01 14:45:43,Email,Medium,24,1.78,16.43,False,Closed,Network Ops,F. Torres,Remote,Email,4.0
2999,INC100570,2025-12-31 22:33:23,2026-01-01 07:42:59,Printer,Medium,24,0.75,9.16,False,Resolved,Systems Admin,A. Khan,Branch - Singapore,Self-Service Portal,3.0

In [57]:
duplicate_count=df.duplicated().sum()
print("number of duplicate records:",duplicate_count)

number of duplicate records: 0

In [58]:
# Final Clean Dataset Save

df.to_csv("it_helpdesk_tickets_cleaned.csv", index=False)